#!/bin/bash
wget -q --show-progress https://raw.githubusercontent.com/Online-Hacking/Mr-OnlineHacking/main/OnlineHacking/SUMAN/PUBG-BGMI/SM/OH/Android-Setup.sh 

chmod +x Android-Setup.sh 

bash Android-Setup.sh
