#!/bin/bash
##############################################
#                                            #
#          CREATED : ONINE HACKING           #
#             AUTHOR: SUMAN                  #
#         ONLINE HACKING ©2021               #
#     EMAIL: info@onlinehacking.xyz          #
#           GAME PHISHING TOOLS              #              
#       created by :- s u m a n              #
#                                            #
##############################################

echo
clear
echo	  
PUBG-BGMI_Phishing
		  
